# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c859dee383575bea131f62c4a0d9f55aa764f0a3a2178690fd188297afde63215047d3497224ee2328d9618ae3c5b6c7b3c1ac94c3d2dc7097f03a71b7c94b75

test:
  secret_key_base: c2bce2e3cd57f78e4a317973b0a02fa6a214b870be974043f38a604047a2b4afb3323e73a14bae60da94933cf81c207d5a3e84b2d93a28ca950651048af7ae45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
